"""Enable SET NULL on unit_id in lesson table

Revision ID: 6ff335e210e8
Revises: 831670efb0af
Create Date: 2025-07-06 17:39:23.165412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff335e210e8'
down_revision = '831670efb0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('lesson_unit_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unit', ['unit_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_unit_id_fkey'), 'unit', ['unit_id'], ['id'])
        batch_op.alter_column('unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
